soundbank/urls.py
"""
urls.py

SoundBank URL Configuration
"""
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth.views import login, logout

import soundbank.views as main_views
import sounds.views as sound_views

urlpatterns = [
    url(r'^$', sound_views.DiscoverView.as_view()),
    url(r'^discover/', sound_views.DiscoverView.as_view()),
    url(r'^upload/', sound_views.UploadView.as_view()),
    url(r'^account/', sound_views.AccountView.as_view()),
    url(r'^sign/', sound_views.SignedS3Request.as_view()),
    url(r'^delete/(?P<pk>\d+)', sound_views.DeleteTrack.as_view()),
    url(r'^register/', main_views.RegisterView.as_view()),
    url(r'^login/', login, {'template_name': 'login.html'}),
    url(r'^logout/', logout, {'next_page': '/discover'}),
    url(r'^admin/', admin.site.urls),
    url('', include('pwa.urls')),
]

sounds/models.py
"""
models.py

Contains database models for Artists, Tracks.
"""
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.dispatch import receiver

import sounds.utils as utils


class Track(models.Model):
    GENRE_CHOICES = (
        ('Blues', 'Blues',),
        ('Classical', 'Classical',),
        ('Country', 'Country',),
        ('Electronic', 'Electronic',),
        ('Folk', 'Folk',),
        ('Jazz', 'Jazz',),
        ('Punk', 'Punk',),
        ('Reggae', 'Reggae',),
        ('Rock', 'Rock',),
    )
    title = models.CharField(max_length=256)
    artist = models.ForeignKey(User)
    genre = models.CharField(max_length=32, choices=GENRE_CHOICES, blank=True, null=True)  # optional
    track = models.CharField(max_length=256)
    image = models.CharField(max_length=256)
    published_date = models.DateField(auto_now=True)
    play_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title


@receiver(models.signals.post_delete, sender=Track)
def delete_track(sender, instance, using, **kwargs):
    """ Removes from S3 on delete """
    base = 'https://s3-eu-west-1.amazonaws.com/{bucket}/'.format(bucket=settings.AWS_S3_BUCKET_NAME)
    image = instance.image.split(base)[1]
    utils.s3_delete_object(image)
    track = instance.track.split(base)[1]
    utils.s3_delete_object(track)

soundbank/forms.py
"""
forms.py

Contains form classes for uploading tracks, and
registering new users.
"""
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    """
    Form to register a user. Saves user
    to django users, and stores name and
    site in Artist model.

    :return: newly created or invalid user
    """
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)

        user.set_password(self.cleaned_data['password2'])
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

sounds/forms.py
"""
forms.py

Contains form classes for uploading tracks.
"""
from django import forms
from sounds.models import Track


class UploadForm(forms.ModelForm):
    """ Form to upload a new track """

    class Meta:
        model = Track
        fields = ['title', 'genre', 'image', 'track']

soundbank/views.py
"""
views.py

Contains main template controls for SoundBank.
"""
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import FormView, TemplateView

from soundbank.forms import RegisterForm


class RegisterView(FormView):
    """
    Form view to register new users.

    """
    template_name = 'register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        form.save(commit=True)
        new_user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password1'])
        login(self.request, new_user)
        return redirect('/upload')


class HomeView(TemplateView):
    template_name = 'home.html'

sounds/views.py
"""
views.py

Contains template controls for Sounds app.
"""
import os
import urllib

from django.views import View
from django.db.models import F
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils.crypto import get_random_string
from django.views.generic import FormView, TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from sounds.models import Track
from sounds.forms import UploadForm
from sounds.utils import s3_sign_request, s3_delete_object


class DiscoverView(TemplateView):
    """
    Return random track on discover page.
    """
    template_name = 'discover.html'

    def get_context_data(self, **kwargs):
        context = super(DiscoverView, self).get_context_data(**kwargs)
        context['track'] = Track.objects.order_by('?').first()
        if context['track']:
            context['track'].play_count = F('play_count') + 1
            context['track'].save()
        return context


class UploadView(LoginRequiredMixin, FormView):
    """
    Upload new track.
    """
    login_url = '/login/'
    template_name = 'upload.html'
    form_class = UploadForm

    def form_valid(self, form):
        form.cleaned_data['artist'] = self.request.user

        form.cleaned_data['image'] = urllib.parse.quote(
            form.cleaned_data['image'], ':/'
        )
        form.cleaned_data['track'] = urllib.parse.quote(
            form.cleaned_data['track'], ':/'
        )
        Track.objects.create(**form.cleaned_data)

        return redirect('/')


class AccountView(LoginRequiredMixin, ListView):
    """
    List of uploaded tracks.
    """
    template_name = 'account.html'
    context_object_name = 'track_list'
    paginate_by = 5

    def get_queryset(self):
        return Track.objects.filter(artist=self.request.user)


class SignedS3Request(View):
    """
    Pre sign a request to directly upload to S3.
    Note: Heroku places a timeout on file uploads, so we need
    to go direct.
    """
    def get(self, request):
        filename, extension = os.path.splitext(request.GET.get('filename'))
        filetype = request.GET.get('filetype')
        guid = get_random_string(length=16)

        if 'image' in filetype:
            name = 'images'
        else:
            name = 'tracks'

        key = 'media/{user}/{name}/{guid}.{ext}'.format(user=self.request.user,
            name=name, guid=guid, ext=extension
        )
        signed = s3_sign_request(key, filetype)
        url = 'https://s3-eu-west-1.amazonaws.com/{bucket}/media/{user}/{name}/{guid}.{ext}'.format(
            bucket=settings.AWS_S3_BUCKET_NAME, user=self.request.user,
            name=name, guid=guid, ext=extension
        )

        return JsonResponse({'signed': signed, 'url': url})


class DeleteTrack(View):
    """
    Request from javascript on account page to delete a track.
    """
    def get(self, request, pk):
        track = Track.objects.get(pk=pk)
        track.delete()

        base = 'https://s3-eu-west-1.amazonaws.com/{bucket}/'.format(bucket=settings.AWS_S3_BUCKET_NAME)
        image = track.image.split(base)[1]
        s3_delete_object(image)
        track = track.track.split(base)[1]
        s3_delete_object(track)

        return JsonResponse({'success': 'deleted'})

templates/account.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}soundbank | account{% endblock %}

{% block content %}

<div class="container flex flex-center flex-column flex-justify">
    <div class="form-box">

        <header>
            <h1>Track List</h1>
        </header>

        {% for track in track_list %}
            <div class="track">
                <span class="left">{{ track.title }}</span>
                <img src="{% static 'img/delete.ico' %}" height="30" width="30"
                     onclick="deleteTrack({{ track.pk }})" class="right" />
            </div>
        {% endfor %}

    </div>
</div>

<script src="{% static 'out/account.js' %}" defer></script>

{% endblock %}

templates/base.html
{% load staticfiles %}
{% load pwa %}
<!DOCTYPE html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %}</title>

	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">

	{% block head %}{% endblock %}
	{% progressive_web_app_meta %}
</head>

<a href="/discover" class="home">soundbank</a>

<body {% if track.image %}
	style="background-image: url({{ track.image }}); position: fixed; background-color: black;"
{% endif %}>

	<nav>
		<a href="#" class="menu">MENU</a>
		<a href="/discover" class="links">discover</a>
		{% if user.is_authenticated %}
			<a href="/upload" class="links">upload</a>
			<a href="/account" class="links">account</a>
			<a href="/logout" class="links">logout</a>
		{% else %}
			<a href="/register" class="links">register</a>
			<a href="/login" class="links">login</a>
		{% endif %}
	</nav>

	{% block content %}
	{% endblock %}

	<script src="{% static 'out/standalone.js' %}" defer></script>
	<script src="{% static 'out/navbar.js' %}" defer></script>

</body>
</html>

templates/discover.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}soundbank | discover{% endblock %}

{% block content %}

<!-- Display centred track name if it exists -->
{% if track.title %}
<div class="title">
  <h1>{{ track.title }}</h1>
</div>
{% endif %}

<!-- Discover next arrow link -->
<a href="/discover">
<button class="arrow-right">
  <svg width="50px" height="50px" viewBox="0 0 50 80">
    <polyline fill="none" stroke="#fff" stroke-width="2"
    		  stroke-linecap="round" stroke-linejoin="round"
    		  points="0.375,0.375 45.63,38.087 0.375,75.8"/>
  </svg>
</button>
</a>

<footer>

  <!-- Play track in player if it exists -->
  {% if track.track %}
  <audio controls autoplay>
    <source src="{{ track.track }}">
  </audio>
  {% endif %}

</footer>

<script src="{% static 'out/swipe.js' %}" defer></script>
<script src="{% static 'out/audio.js' %}" defer></script>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}soundbank{% endblock %}

{% block content %}

<div class="logo">
	<h1><span>The</span></h1>
	<h1><span>Sound</span></h1>
	<h1><span>Bank</span></h1>
</div>

<!-- Discover next arrow link -->
<a href="/discover">
<button class="arrow-right">
  <svg width="60px" height="80px" viewBox="0 0 50 80">
    <polyline fill="none" stroke="#121212" stroke-width="2"
    		  stroke-linecap="round" stroke-linejoin="round"
    		  points="0.375,0.375 45.63,38.087 0.375,75.8"/>
  </svg>
</button>
</a>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}soundbank | login{% endblock %}

{% block content %}

<div class="container flex flex-center flex-column flex-justify">
    <div class="form-box">
        {% if form.errors %}
            <p style="color: red;">
                Please correct the error{{ form.errors|pluralize }} below.
            </p>
        {% endif %}

        <header>
            <h1>Artist Login</h1>
        </header>

        <form action="" method="post">
            {% csrf_token %}

            <div class="form-input">
                <label for="id_username">Username</label>
                <input id="id_username" name="username" type="text"
                       {% if form.username.value %} value="{{ form.username.value }}" {% endif %} />
                {% if form.username.errors %}
                    <div class="errors">{{ form.username.errors|striptags }}</div>
                {% endif %}
            </div>

            <div class="form-input">
                <label for="id_password">Password</label>
                <input id="id_password" name="password" type="password"
                       {% if form.password.value %} value="{{ form.password.value }}" {% endif %} />
                {% if form.password.errors %}
                    <div class="errors">{{ form.password.errors|striptags }}</div>
                {% endif %}
            </div>

            <div class="form-end">
                <button type="submit" class="btn">Login</button>
            </div>

        </form>
    </div>
</div>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}soundbank | register{% endblock %}

{% block content %}

<div class="container flex flex-center flex-column flex-justify">
    <div class="form-box">

        {% if form.errors %}
            <p style="color: red;">
                Please correct the error{{ form.errors|pluralize }} below.
            </p>
        {% endif %}

        <header>
            <h1>Register Artist</h1>
        </header>

        <form action="" method="post">
            {% csrf_token %}

            <div class="form-input">
                <label for="id_username">Username</label>
                <input id="id_username" name="username" type="text"
                       {% if form.username.value %} value="{{ form.username.value }}" {% endif %} />
                {% if form.username.errors %}
                    <div class="errors">{{ form.username.errors|striptags }}</div>
                {% endif %}
            </div>

            <div class="form-input">
                <label for="id_email">Email</label>
                <input id="id_email" name="email" type="email"
                       {% if form.email.value %} value="{{ form.email.value }}" {% endif %} />
                {% if form.email.errors %}
                    <div class="errors">{{ form.email.errors|striptags }}</div>
                {% endif %}
            </div>

            <div class="form-input">
                <label for="id_password1">Password</label>
                <input id="id_password1" name="password1" type="password"
                       {% if form.password1.value %} value="{{ form.password1.value }}" {% endif %} />
                {% if form.password1.errors %}
                    <div class="errors">{{ form.password1.errors|striptags }}</div>
                {% endif %}
            </div>

            <div class="form-input">
                <label for="id_password2">Confirm Password</label>
                <input id="id_password2" name="password2" type="password"
                       {% if form.password2.value %} value="{{ form.password2.value }}" {% endif %} />
                {% if form.password2.errors %}
                    <div class="errors">{{ form.password2.errors|striptags }}</div>
                {% endif %}
            </div>

            <div class="form-end">
                <button type="submit" class="btn">Register</button>
            </div>

        </form>
    </div>
</div>

{% endblock %}

templates/upload.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}soundbank | upload{% endblock %}
{% block head %}

{% endblock %}

{% block content %}

<div class="container flex flex-center flex-column flex-justify">
    <div class="form-box">

        <header>
            <h1>Upload Track</h1>
        </header>

        {% if form.errors %}
            <p style="color: red;">
                Please correct the error{{ form.errors|pluralize }} below.
            </p>
        {% endif %}

        <form action="" method="post">
            {% csrf_token %}

            <div class="form-input">
                <label for="id_title">Title</label>
                <input id="id_title" name="title" type="text" required
                       {% if form.title.value %} value="{{ form.title.value }}" {% endif %} />
                {% if form.title.errors %}
                    <div class="errors">{{ form.title.errors|striptags }}</div>
                {% endif %}
            </div>

            <div class="form-input">
                <label for="id_genre">Genre</label>
                <select id="id_genre" name="genre">
                    {% for value, text in form.fields.genre.choices %}
                        <option value="{{ value }}">{{ text }}</option>
                    {% endfor %}
                </select>
                {% if form.genre.errors %}
                    <div class="errors">{{ form.genre.errors|striptags }}</div>
                {% endif %}
            </div>

            <div class="upload">
                <div class="form-input-file">
                    <div class="btn input-btn">
                        <span>Cover Image</span>
                        <input id="image" type="file" accept="image/*" required />
                    </div>
                    {% if form.image.errors %}
                        <div class="errors">{{ form.image.errors|striptags }}</div>
                    {% endif %}
                </div>

                <div class="form-input-file">
                    <div class="btn input-btn">
                        <span>Audio Track</span>
                        <input id="track" type="file" accept="audio/*" required />
                    </div>
                    {% if form.track.errors %}
                        <div class="errors">{{ form.track.errors|striptags }}</div>
                    {% endif %}
                </div>
            </div>

            <div id="loading">
                <img src="{% static 'img/loading.gif' %}" />
            </div>

            <!-- JS writes S3 image/track URL to hidden field for Django model -->
            <input id="id_image" name="image" hidden />
            <input id="id_track" name="track" hidden />

            <div class="upload-form-end">
                <button id="submit" class="btn" type="submit">Upload</button>
            </div>

        </form>
    </div>
</div>


<script src="{% static 'out/signS3.js' %}" defer></script>

{% endblock %}